default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch("MYSQLHOST") { "localhost" } %>
  username: <%= ENV.fetch("MYSQLUSER") { "root" } %>
  password: <%= ENV.fetch("MYSQLPASS") { "" } %>
  port: <%= ENV.fetch("MYSQLPASS") { 3306 } %>
  sslca: <%= ENV.fetch("MYSQLCA") { "" } %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQLDB") { "db" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("MYSQLDB") { "db" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("MYSQLDB") { "db" } %>